name: tests

on:
  workflow_dispatch:
  push:
    branches: ['main', 'dev-*']
  pull_request:
  release:
    types: [published]

jobs:
  tests:
    name: "Tests"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements/requirements_dev.txt
          python -m pip install -e .
      - name: Run Tests
        run: |
          pytest
#          pytest --cov --cov-report xml . # set up codecov to run this
      # - name: Upload coverage
      #   uses: codecov/codecov-action@v2
